# Generated by Django 4.2.5 on 2023-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto_title', models.CharField(max_length=150, verbose_name='название')),
                ('moto_description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
                'ordering': ('moto_title',),
            },
        ),
    ]
