# Generated by Django 4.2.5 on 2023-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_car_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ('-id',), 'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
    ]
